import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e3e2e0",
        "on-tertiary-fixed-variant": "#5e4200",
        "on-background": "#1a1c1b",
        "secondary-container": "#febe9e",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3130",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#271900",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        tertiary: "#7c5800",
        "primary-fixed-dim": "#a3d1af",
        "outline-variant": "#c1c9c0",
        "tertiary-fixed-dim": "#f3be58",
        "surface-container": "#efeeec",
        "on-secondary-fixed": "#331201",
        "surface-container-low": "#f4f3f1",
        "on-primary-container": "#214b32",
        "error-container": "#ffdad6",
        "on-surface-variant": "#414942",
        surface: "#faf9f7",
        "surface-tint": "#3c674b",
        "tertiary-fixed": "#ffdea6",
        "secondary-fixed": "#ffdbcb",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1b",
        "primary-fixed": "#beeeca",
        "surface-container-high": "#e9e8e6",
        "on-primary-fixed-variant": "#244f35",
        "inverse-on-surface": "#f1f1ef",
        background: "#faf9f7",
        primary: "#3c674b",
        "tertiary-container": "#daa844",
        "on-tertiary-container": "#593e00",
        "on-secondary-fixed-variant": "#673c24",
        "on-secondary-container": "#794b31",
        secondary: "#835339",
        "surface-dim": "#dadad8",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a3d1af",
        "on-primary-fixed": "#00210f",
        "secondary-fixed-dim": "#f8b898",
        "primary-container": "#8dbb9a",
        outline: "#717972",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e3e2e0",
        "surface-bright": "#faf9f7",
        "soft-rose": "#D28080",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta-sans)"],
        body: ["var(--font-be-vietnam-pro)"],
        label: ["var(--font-be-vietnam-pro)"],
        display: ["var(--font-luckiest-guy)"],
        handwritten: ["var(--font-amatic-sc)"],
        accent: ["var(--font-pacifico)"],
        reading: ["var(--font-raleway)"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
